const BASE='/wh3-diplomacy/';
const DATA=BASE+'data/generated/';
const aliases={karl:['karl','karl_franz'],kroq:['kroq','kroq_gar'],fay:['fay','fay_enchantress'],sisters:['sisters','sisters_of_twilight'],kugath:['kugath','ku_gath'],nkari:['nkari','n_kari'],belakor:['belakor','be_lakor'],daemon:['daemon','daemon_prince']};
const player=document.querySelector('#player'),deal=document.querySelector('#deal'),race=document.querySelector('#race'),query=document.querySelector('#query'),categoryFilter=document.querySelector('#category'),results=document.querySelector('#results'),summary=document.querySelector('#summary');
let lords=[],initialRelations=[];
function words(v){return String(v||'').toLowerCase().split(/[^a-z0-9]+/).filter(Boolean)}
function scoreLeaderMatch(row,id){let best=0;for(const alias of (aliases[id]||[id])){const aw=words(alias);for(const [value,weight] of [[row.agentSubtype,30],[row.politicalPartyKey,20],[row.factionKey,10]]){const vw=words(value);if(aw.length===1&&vw.includes(aw[0]))best=Math.max(best,weight);else if(aw.every(w=>vw.includes(w)))best=Math.max(best,weight+aw.length)}}return best}
function parseGroups(source){const match=source.match(/const groups=(\{[\s\S]*?\n\};)/);if(!match)throw new Error('Roster introuvable');return Function('return '+match[1].slice(0,-1))()}
function culturalRelation(a,b){return a.key&&b.key?initialRelations.find(r=>r.sourceFaction===a.key&&r.targetFaction===b.key)||null:null}
function category(v){if(v>=15)return['Favorable','good'];if(v<=-15)return['Hostile','bad'];return['Neutre','mid']}
function render(){const me=lords.find(l=>l.id===player.value);if(!me)return;const filter=race.value,needle=query.value.trim().toLowerCase(),wantedCategory=categoryFilter.value;const rows=lords.filter(l=>l.id!==me.id&&(!filter||l.race===filter)).map(l=>{const relation=culturalRelation(me,l),base=relation?Number(relation.baseAttitude):null;const [label,cls]=base===null?['Non résolu','mid']:category(base);return{lord:l,base,label,cls,relation}}).filter(row=>(!needle||`${row.lord.name} ${row.lord.faction} ${row.lord.race}`.toLowerCase().includes(needle))&&(!wantedCategory||row.cls===wantedCategory)).sort((a,b)=>{if(a.relation?.atWar!==b.relation?.atWar)return a.relation?.atWar?1:-1;if(a.base===null&&b.base!==null)return 1;if(a.base!==null&&b.base===null)return-1;return(b.base??-999)-(a.base??-999)});
summary.innerHTML=`<span class="pill"><b>${me.name}</b> · ${me.faction}</span><span class="pill">${deal.value}</span><span class="pill">${rows.length} partenaires affichés</span>`;
results.innerHTML=rows.map(({lord,base,label,cls,relation})=>{const factors=(relation?.components||[]).map(c=>c.type==='cai-personality-cultural-override'?`Surcharge de personnalité CAI : ${c.personalityComponent}.`:`Base culturelle directionnelle (${me.race} → ${lord.race}).`).join(' ');return `<div class="row"><div><strong>${lord.name}</strong><small>${lord.faction}</small></div><div class="race">${lord.race}</div><div><span class="score ${cls}">${base===null?'—':(base>0?'+':'')+base}</span><small>${label}</small></div><div class="status">${relation?.atWar?'<span class="tag war">En guerre au départ</span>':relation?.treaties?.length?'<span class="tag">Traité au départ</span>':'<span class="tag">Diplomatie normale</span>'}</div><details class="explain"><summary>Voir les composantes connues</summary><ul><li>${relation?`${factors} Valeur ${base>0?'+':''}${base}.`:'Base culturelle non résolue pour cette paire.'}</li>${relation?`<li>Multiplicateurs : positif ×${relation.positiveAttitudeMultiplier}, négatif ×${relation.negativeAttitudeMultiplier}.</li>`:''}<li>${relation?.atWar?'Guerre explicite dans le startpos.':relation?.treaties?.length?'Traités explicites : '+relation.treaties.join(', ')+'.':'Aucune guerre ni traité explicite dans le startpos extrait.'}</li><li>Les facteurs dynamiques (fiabilité, guerres, puissance, corruption et événements) ne sont pas estimés avant une partie.</li></ul></details></div>`}).join('')||'<div class="empty">Aucun partenaire.</div>'}
Promise.all([
fetch(BASE+'roster.js',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error('roster HTTP '+r.status);return r.text()}),
fetch(DATA+'frontend-leaders.json',{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject(new Error('leaders HTTP '+r.status))),
fetch(DATA+'initial-diplomacy.json',{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject(new Error('initial diplomacy HTTP '+r.status)))
]).then(([rosterSource,leaderData,initialData])=>{const groups=parseGroups(rosterSource),requestedLeader=new URLSearchParams(window.location.search).get('leader');lords=Object.entries(groups).flatMap(([raceName,arr])=>arr.map(([id,name,faction])=>({id,name,faction,race:raceName,key:null})));const rows=leaderData.leaders||[];for(const lord of lords){const matches=rows.map(row=>({row,score:scoreLeaderMatch(row,lord.id)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score);if(matches.length&&(!matches[1]||matches[0].score>matches[1].score))lord.key=matches[0].row.factionKey}initialRelations=initialData.relations||[];const selected=lords.some(lord=>lord.id===requestedLeader)?requestedLeader:'imrik';player.innerHTML=Object.entries(groups).map(([r,arr])=>`<optgroup label="${r}">${arr.map(([id,n,f])=>`<option value="${id}" ${id===selected?'selected':''}>${n} — ${f}</option>`).join('')}</optgroup>`).join('');race.innerHTML='<option value="">Toutes les races</option>'+Object.keys(groups).map(r=>`<option>${r}</option>`).join('');render()}).catch(err=>{console.error(err);results.innerHTML=`<div class="empty">Erreur de chargement : ${err.message}</div>`});
player.onchange=render;deal.onchange=render;race.onchange=render;query.oninput=render;categoryFilter.onchange=render;
