const BASE='/wh3-diplomacy/';
const DATA=BASE+'data/generated/';
const raceToSubculture={"L'Empire":'wh_main_sc_emp_empire','Nains':'wh_main_sc_dwf_dwarfs','Hauts Elfes':'wh2_main_sc_hef_high_elves','Elfes Noirs':'wh2_main_sc_def_dark_elves','Hommes-lézards':'wh2_main_sc_lzd_lizardmen','Skavens':'wh2_main_sc_skv_skaven','Côte Vampire':'wh2_dlc11_sc_cst_vampire_coast','Comtes Vampires':'wh_main_sc_vmp_vampire_counts','Rois des Tombes':'wh2_dlc09_sc_tmb_tomb_kings','Peaux-Vertes':'wh_main_sc_grn_greenskins','Bretonnie':'wh_main_sc_brt_bretonnia','Elfes Sylvains':'wh_dlc05_sc_wef_wood_elves','Hommes-bêtes':'wh_dlc03_sc_bst_beastmen','Norsca':'wh_dlc08_sc_nor_norsca','Kislev':'wh3_main_sc_ksl_kislev','Grand Cathay':'wh3_main_sc_cth_cathay','Khorne':'wh3_main_sc_kho_khorne','Nurgle':'wh3_main_sc_nur_nurgle','Tzeentch':'wh3_main_sc_tze_tzeentch','Slaanesh':'wh3_main_sc_sla_slaanesh','Royaumes Ogres':'wh3_main_sc_ogr_ogre_kingdoms','Nains du Chaos':'wh3_dlc23_sc_chd_chaos_dwarfs','Guerriers du Chaos':'wh_main_sc_chs_chaos','Démons du Chaos':'wh3_main_sc_dae_daemons'};
const aliases={karl:['karl','karl_franz'],kroq:['kroq','kroq_gar'],fay:['fay','fay_enchantress'],sisters:['sisters','sisters_of_twilight'],kugath:['kugath','ku_gath'],nkari:['nkari','n_kari'],belakor:['belakor','be_lakor'],daemon:['daemon','daemon_prince']};
const player=document.querySelector('#player'),deal=document.querySelector('#deal'),race=document.querySelector('#race'),results=document.querySelector('#results'),summary=document.querySelector('#summary');
let lords=[],cultural=[],explicit=[];
function words(v){return String(v||'').toLowerCase().split(/[^a-z0-9]+/).filter(Boolean)}
function scoreLeaderMatch(row,id){let best=0;for(const alias of (aliases[id]||[id])){const aw=words(alias);for(const [value,weight] of [[row.agentSubtype,30],[row.politicalPartyKey,20],[row.factionKey,10]]){const vw=words(value);if(aw.length===1&&vw.includes(aw[0]))best=Math.max(best,weight);else if(aw.every(w=>vw.includes(w)))best=Math.max(best,weight+aw.length)}}return best}
function parseGroups(source){const match=source.match(/const groups=(\{[\s\S]*?\n\};)/);if(!match)throw new Error('Roster introuvable');return Function('return '+match[1].slice(0,-1))()}
function culturalRelation(a,b){const s=raceToSubculture[a.race],t=raceToSubculture[b.race];return cultural.find(r=>r.sourceSubculture===s&&r.targetSubculture===t)||null}
function explicitRelation(a,b){return a.key&&b.key?explicit.find(r=>r.sourceFaction===a.key&&r.targetFaction===b.key)||null:null}
function category(v){if(v>=15)return['Favorable','good'];if(v<=-15)return['Hostile','bad'];return['Neutre','mid']}
function render(){const me=lords.find(l=>l.id===player.value);if(!me)return;const filter=race.value;const rows=lords.filter(l=>l.id!==me.id&&(!filter||l.race===filter)).map(l=>{const c=culturalRelation(me,l),e=explicitRelation(me,l);const base=c?Number(c.attitudeBase):null;const [label,cls]=base===null?['Non résolu','mid']:category(base);return{lord:l,base,label,cls,explicit:e}}).sort((a,b)=>{if(a.explicit?.atWar!==b.explicit?.atWar)return a.explicit?.atWar?1:-1;if(a.base===null&&b.base!==null)return 1;if(a.base!==null&&b.base===null)return-1;return(b.base??-999)-(a.base??-999)});
summary.innerHTML=`<span class="pill"><b>${me.name}</b> · ${me.faction}</span><span class="pill">${deal.value}</span><span class="pill">${rows.length} partenaires affichés</span>`;
results.innerHTML=rows.map(({lord,base,label,cls,explicit:e})=>`<div class="row"><div><strong>${lord.name}</strong><small>${lord.faction}</small></div><div class="race">${lord.race}</div><div><span class="score ${cls}">${base===null?'—':(base>0?'+':'')+base}</span><small>${label}</small></div><div class="status">${e?.atWar?'<span class="tag war">En guerre au départ</span>':e?.treaties?.length?'<span class="tag">Traité au départ</span>':'<span class="tag">Diplomatie normale</span>'}</div></div>`).join('')||'<div class="empty">Aucun partenaire.</div>'}
Promise.all([
fetch(BASE+'roster.js',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error('roster HTTP '+r.status);return r.text()}),
fetch(DATA+'frontend-leaders.json',{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject(new Error('leaders HTTP '+r.status))),
fetch(DATA+'cultural-relations.json',{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject(new Error('culture HTTP '+r.status))),
fetch(DATA+'immortal-empires-startpos.json',{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject(new Error('startpos HTTP '+r.status)))
]).then(([rosterSource,leaderData,culturalData,startposData])=>{const groups=parseGroups(rosterSource);lords=Object.entries(groups).flatMap(([raceName,arr])=>arr.map(([id,name,faction])=>({id,name,faction,race:raceName,key:null})));const rows=leaderData.leaders||[];for(const lord of lords){const matches=rows.map(row=>({row,score:scoreLeaderMatch(row,lord.id)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score);if(matches.length&&(!matches[1]||matches[0].score>matches[1].score))lord.key=matches[0].row.factionKey}cultural=culturalData.relations||[];explicit=startposData.relations||[];player.innerHTML=Object.entries(groups).map(([r,arr])=>`<optgroup label="${r}">${arr.map(([id,n,f])=>`<option value="${id}" ${id==='imrik'?'selected':''}>${n} — ${f}</option>`).join('')}</optgroup>`).join('');race.innerHTML='<option value="">Toutes les races</option>'+Object.keys(groups).map(r=>`<option>${r}</option>`).join('');render()}).catch(err=>{console.error(err);results.innerHTML=`<div class="empty">Erreur de chargement : ${err.message}</div>`});
player.onchange=render;deal.onchange=render;race.onchange=render;
