const groups={
  "L'Empire":[["karl","Empereur Karl Franz","Reikland"],["gelt","Balthasar Gelt","L'Ordre Doré"],["volkmar","Volkmar le Sévère","Culte de Sigmar"],["markus","Markus Wulfhart","L'Expédition du jagdsmarshall"],["elspeth","Elspeth von Draken","Wissenland et Nuln"]],
  "Nains":[["thorgrim","Thorgrim le Rancunier","Karaz-a-Karak"],["grombrindal","Grombrindal","Le Throng ancestral"],["ungrim","Ungrim Poing de Fer","Karak Kadrin"],["belegar","Belegar Marteau-de-fer","Clan Angrund"],["thorek","Thorek Tête en Fer","Expédition de Tête-en-fer"],["malakai","Malakai Makaisson","Maîtres de l'Innovation"]],
  "Hauts Elfes":[["tyrion","Tyrion","Eataine"],["teclis","Teclis","Ordre des maîtres du savoir"],["alarielle","Alarielle la Radieuse","Avelorn"],["alith","Alith Anar","Nagarythe"],["eltharion","Eltharion le Sinistre","Yvresse"],["imrik","Imrik","Chevaliers de Caledor"],["aislinn","Seigneur des Mers Aislinn","Patrouille Maritime des Hauts Elfes"]],
  "Elfes Noirs":[["malekith","Malékith","Naggarond"],["morathi","Morathi","Culte du Plaisir"],["hellebron","Hellebron l'Ancienne","Har Ganeth"],["lokhir","Lokhir Cœur de Pierre","L'Effroi Béni"],["malus","Malus Darkblade","Hag Graef"],["rakarth","Rakarth","Les Mille Gueules"]],
  "Hommes-lézards":[["mazdamundi","Seigneur Mazdamundi","Hexoatl"],["kroq","Kroq-Gar","Ultimes Défenseurs"],["tehenhauin","Tehenhauin","Culte de Sotek"],["tiktaqto","Tiktaq'to","Tlaqua"],["gorrok","Gor-Rok","Itza"],["nakai","Nakai le Vagabond","Esprit de la jungle"],["oxyotl","Oxyotl","Fantômes de Pahuax"]],
  "Skavens":[["queek","Queek Coupe-Têtes","Clan Mors"],["skrolk","Seigneur Skrolk","Clan Pestilens"],["tretch","Tretch la-Queue-qui-Frétille","Clan Rictus"],["ikit","Ikit la Griffe","Clan Skryre"],["snikch","Maître Assassin Snikch","Clan Eshin"],["throt","Throt le Galeux","Clan Moulder"]],
  "Côte Vampire":[["luthor","Luthor Harkon","L'Éveillé"],["noctilus","Comte Noctilus","La Flotte de Terreur"],["aranessa","Aranessa Saumâtre","Pirates de Sartosa"],["cylostra","Cylostra Mauvaileron","Les Noyés"]],
  "Comtes Vampires":[["mannfred","Mannfred von Carstein","Le Conclave de Drakenhof"],["vlad","Vlad von Carstein","Sylvanie"],["isabella","Isabella von Carstein","Sylvanie"],["kemmler","Heinrich Kemmler","La Légion du Tertre"],["ghorst","Helman Ghorst","Caravane des Roses bleues"]],
  "Rois des Tombes":[["settra","Settra l'Impérissable","Khemri"],["arkhan","Arkhan le Noir","Fidèles de Nagash"],["khalida","Haute Reine Khalida","Cour de Lybaras"],["khatep","Khatep le Haut Hiérophante","Exilés de Nehek"]],
  "Peaux-Vertes":[["grimgor","Grimgor Boît'en Fer","Les Durs à Kuir' de Grimgor"],["azhag","Azhag le Massacreur","Zagiteurs d'Os"],["skarsnik","Skarsnik","La Lune Crochue"],["wurrzag","Wurrzag","Les Mains sanglantes"],["grom","Grom la Panse","Haches brisées"],["gorbad","Gorbad Griff' Eud' Fer","Orques de Griff' Eud' Fer"]],
  "Bretonnie":[["louen","Roy Louen Cœur de Lion","Couronne"],["fay","Fée Enchanteresse","Gasconnie"],["alberic","Albéric de Bordeleaux","Errants de Bordeleaux"],["repanse","Jeanne de Lyonesse","Chevaliers de Lyonesse"]],
  "Elfes Sylvains":[["orion","Orion","Talsyn"],["durthu","Durthu","Argwylon"],["sisters","Sœurs du Crépuscule","Hérauts d'Ariel"],["drycha","Drycha","Bosquet de guerre du Malheur"]],
  "Hommes-bêtes":[["khazrak","Khazrak le Borgne","Harde de Khazrak le Borgne"],["malagor","Malagor Mauvais-Présage","Émissaire du Désastre"],["morghur","Morghur l'Enfant de l'Ombre","Harde guerrière de l'Enfant de l'Ombre"],["taurox","Taurox le Taureau d'Airain","Tribu de Cornegouge"]],
  "Norsca":[["wulfrik","Wulfrik le Vagabond","Marche-mondes"],["throgg","Throgg","Croc de l'Hiver"],["sayl","Sayl le Perfide","Dolgans"]],
  "Kislev":[["katarin","Tsarine Katarina","La Cour de Givre"],["kostaltyn","Kostaltyn","La Grande Orthodoxie"],["boris","Boris Ursus","Revivalistes d'Ursun"],["ostankya","Mère Ostankya","Filles de la Forêt"]],
  "Grand Cathay":[["miao","Miao Ying","Provinces du Nord"],["zhao","Zhao Ming","Provinces de l'Ouest"],["yuan","Yuan Bo, le Dragon de Jade","La Cour de Jade"],["bhashiva","Bhashiva, le Tigre Blanc","Griffes du Tigre Blanc"]],
  "Khorne":[["skarbrand","Skarbrand l'Exilé","Exilés de Khorne"],["skulltaker","Preneur de Crânes","Vagabonds rouges"],["arbaal","Arbaal l'Invaincu","Prétendants de Khorne"]],
  "Nurgle":[["kugath","Ku'gath, Père des Épidémies","Véroleurs de Nurgle"],["tamurkhan","Tamurkhan le Seigneur des Vers","L'Ost des Vers"],["epidemius","Epidemius","Intendants de la Pestilence"]],
  "Tzeentch":[["kairos","Kairos Tisseur de Destins","Oracles de Tzeentch"],["changeling","Le Changelin","Les Trompeurs"]],
  "Slaanesh":[["nkari","N'Kari","Séducteurs de Slaanesh"],["dechala","Déchala la Répudiée","Les Tourmenteurs"],["masque","Le Masque de Slaanesh","La Troupe Maudite"]],
  "Royaumes Ogres":[["greasus","Graissus Dent d'Or","Dent d'Or"],["skrag","Skrag le Désosseur","Disciples de La Gueule"],["golgfag","Golgfag Mangeur d'Hommes","Les Mangeurs d'Hommes"]],
  "Nains du Chaos":[["astragoth","Astragoth Main-de-Fer","Disciples d'Hashut"],["drazhoath","Drazhoath le Cendreux","La Légion d'Azgorh"],["zhatan","Zhatan le Noir","L'Ost de guerre de Zharr"]],
  "Guerriers du Chaos":[["archaon","Archaon, Seigneur de la Fin des Temps","Ost de guerre de l'Apocalypse"],["kholek","Kholek Dévore-le-Soleil","Hérauts des Tempêtes"],["sigvald","Prince Sigvald le Magnifique","L'Ost Décadent"],["belakor","Be'lakor","Légion des Ombres"],["azazel","Azazel","Les Légions Extatiques"],["festus","Docteur Festus","Les Fécondés"],["vilitch","Vilitch le Maudit","Marionnettes de l'Anarchie"],["valkia","Valkia la Sanglante","Légion de la Reine du Carnage"]],
  "Démons du Chaos":[["daemon","Prince Démon","Légion du Chaos"]]
};

const fallbackFactionKeys={imrik:'wh2_dlc15_hef_imrik',karl:'wh_main_emp_empire',malus:'wh2_main_def_hag_graef',kugath:'wh3_main_nur_poxmakers_of_nurgle'};
const fallbackPositions={imrik:[573.586609,330.326599],karl:[355.687042,487.026276],malus:[393.503754,719.28479],kugath:[668.102417,288.452148]};
const aliases={karl:['karl','karl_franz'],kroq:['kroq','kroq_gar'],fay:['fay','fay_enchantress'],sisters:['sisters','sisters_of_twilight'],kugath:['kugath','ku_gath'],nkari:['nkari','n_kari'],belakor:['belakor','be_lakor'],daemon:['daemon','daemon_prince']};
const lords=Object.entries(groups).flatMap(([race,a])=>a.map(([id,name,faction])=>({id,name,faction,race,key:fallbackFactionKeys[id]||null})));
const positions={...fallbackPositions};
const roster=document.querySelector('#roster'),selected=document.querySelector('#selected'),matrix=document.querySelector('#matrix'),map=document.querySelector('#map'),mapViewport=document.querySelector('#mapViewport'),mapStatus=document.querySelector('#mapStatus'),search=document.querySelector('#search'),raceFilter=document.querySelector('#raceFilter');
let relations=[],positionRecords=[],positionBounds=null,zoom=1,offset={x:0,y:0},drag=null,metadataLoading=true;
const selectedIds=new Set(['imrik','karl']);
const chosen=()=>[...selectedIds];
function initRaceFilter(){raceFilter.innerHTML=Object.keys(groups).map(r=>`<option value="${r}">${r}</option>`).join('');raceFilter.value=Object.keys(groups)[0]}
function renderRoster(){const q=search.value.trim().toLowerCase(),race=raceFilter.value,all=groups[race]||[];const list=all.filter(x=>(race+' '+x[1]+' '+x[2]).toLowerCase().includes(q));roster.innerHTML=`<section class="race"><h3>${race} <small>(${list.length}/${all.length})</small></h3><div class="lords">${list.map(([id,n,f])=>`<label class="lord"><input type="checkbox" value="${id}" ${selectedIds.has(id)?'checked':''}><span><strong>${n}</strong><small>${f}</small></span></label>`).join('')}</div>${list.length?'':'<p class="pending">Aucun seigneur ne correspond à la recherche.</p>'}</section>`}
function rel(a,b){return relations.find(r=>r.sourceFaction===a&&r.targetFaction===b)}
function applyMapTransform(){map.style.transform=`translate(${offset.x}px,${offset.y}px) scale(${zoom})`}
function calculateBounds(records){if(!records.length)return null;const xs=records.map(p=>p.x),ys=records.map(p=>p.y);return{minX:Math.min(...xs),maxX:Math.max(...xs),minY:Math.min(...ys),maxY:Math.max(...ys)}}
function mapPercent(x,y){const b=positionBounds;if(!b||b.maxX===b.minX||b.maxY===b.minY)return[50,50];const pad=2.5;return[pad+(x-b.minX)/(b.maxX-b.minX)*(100-pad*2),pad+(b.maxY-y)/(b.maxY-b.minY)*(100-pad*2)]}
function renderMap(ids){map.innerHTML='';let missing=0;ids.forEach(id=>{if(!positions[id]){missing++;return}const l=lords.find(x=>x.id===id),[x,y]=positions[id],m=document.createElement('div');m.className='marker';const[left,top]=mapPercent(x,y);m.style.left=`${left}%`;m.style.top=`${top}%`;m.innerHTML=`<span class="marker-dot"></span><span class="marker-label"><b>${l.name}</b><small>${l.faction}</small></span>`;map.append(m)});if(metadataLoading)mapStatus.textContent='Chargement des positions WH3 vérifiées…';else if(missing)mapStatus.textContent=`${missing} position(s) sélectionnée(s) non résolue(s) dans le dump courant. Aucun emplacement approximatif n'est inventé.`;else mapStatus.textContent='Toutes les positions sélectionnées proviennent de cam_gameplay_start dans les scripts WH3.';applyMapTransform()}
function renderSelected(ids){const items=ids.map(id=>lords.find(l=>l.id===id)).filter(Boolean);selected.innerHTML=`<p>${items.length} dirigeant${items.length>1?'s':''} sélectionné${items.length>1?'s':''} · aucune limite fixe</p><div class="selected-lords">${items.map(l=>`<span class="selected-chip"><b>${l.name}</b><small>${l.race}</small><button type="button" data-remove="${l.id}" title="Retirer ${l.name}">×</button></span>`).join('')}</div>`}
function render(){const ids=chosen(),a=ids.map(id=>lords.find(l=>l.id===id)).filter(Boolean);renderSelected(ids);renderMap(ids);if(ids.length<2){matrix.innerHTML='<p class="pending">Sélectionne au moins deux dirigeants.</p>';return}matrix.innerHTML='<table><tr><th>De / vers</th>'+a.map(l=>`<th>${l.name}</th>`).join('')+'</tr>'+a.map(x=>`<tr><th>${x.name}</th>`+a.map(y=>{if(x.id===y.id)return'<td>—</td>';const r=x.key&&y.key?rel(x.key,y.key):null;return r?`<td class="${r.atWar?'bad':''}">${r.atWar?'En guerre':r.treaties.length?'Traité':'Relation explicite'}</td>`:'<td class="pending">Pas de relation explicite</td>'}).join('')+'</tr>').join('')+'</table>'}
function words(value){return String(value||'').toLowerCase().split(/[^a-z0-9]+/).filter(Boolean)}
function scoreLeaderMatch(row,id){const wanted=aliases[id]||[id];const fields=[[row.agentSubtype,30],[row.politicalPartyKey,20],[row.factionKey,10]];let best=0;for(const alias of wanted){const aliasWords=words(alias);for(const[value,weight]of fields){const valueWords=words(value);if(aliasWords.length===1&&valueWords.includes(aliasWords[0]))best=Math.max(best,weight);else if(aliasWords.every(w=>valueWords.includes(w)))best=Math.max(best,weight+aliasWords.length)}}return best}
function applyLeaderMetadata(leadersData,positionsData){const rows=leadersData.leaders||[];positionRecords=positionsData.positions||[];positionBounds=calculateBounds(positionRecords);for(const lord of lords){const scored=rows.map(row=>({row,score:scoreLeaderMatch(row,lord.id)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score);if(scored.length&&(!scored[1]||scored[0].score>scored[1].score))lord.key=scored[0].row.factionKey;if(lord.key){const pos=positionRecords.find(p=>p.factionKey===lord.key);if(pos)positions[lord.id]=[pos.x,pos.y]}}}
function setFooter(){const keyed=lords.filter(l=>l.key).length,located=lords.filter(l=>positions[l.id]).length;document.querySelector('footer').textContent=`Roster ${lords.length} seigneurs · ${keyed} factions résolues · ${located} positions de départ résolues · ${relations.length} relations explicites`}
roster.addEventListener('change',e=>{if(!e.target.matches('input[type="checkbox"]'))return;e.target.checked?selectedIds.add(e.target.value):selectedIds.delete(e.target.value);render()});selected.addEventListener('click',e=>{const button=e.target.closest('[data-remove]');if(!button)return;selectedIds.delete(button.dataset.remove);renderRoster();render()});raceFilter.onchange=()=>{search.value='';renderRoster()};search.oninput=renderRoster;plus.onclick=()=>{zoom=Math.min(3,zoom+.25);applyMapTransform()};minus.onclick=()=>{zoom=Math.max(1,zoom-.25);if(zoom===1)offset={x:0,y:0};applyMapTransform()};reset.onclick=()=>{zoom=1;offset={x:0,y:0};applyMapTransform()};mapViewport.addEventListener('pointerdown',e=>{drag={x:e.clientX,y:e.clientY,ox:offset.x,oy:offset.y};mapViewport.classList.add('dragging');mapViewport.setPointerCapture(e.pointerId)});mapViewport.addEventListener('pointermove',e=>{if(!drag)return;offset={x:drag.ox+e.clientX-drag.x,y:drag.oy+e.clientY-drag.y};applyMapTransform()});mapViewport.addEventListener('pointerup',()=>{drag=null;mapViewport.classList.remove('dragging')});mapViewport.addEventListener('pointercancel',()=>{drag=null;mapViewport.classList.remove('dragging')});
initRaceFilter();renderRoster();render();
const dataBase='./data/runtime/';
const loadJson=name=>fetch(`${dataBase}${name}?v=20260902-3`,{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error(`${name} HTTP ${r.status}`);return r.json()});
Promise.allSettled([loadJson('immortal-empires-startpos.json'),loadJson('frontend-leaders.json'),loadJson('campaign-start-positions.json')]).then(([relationsResult,leadersResult,positionsResult])=>{if(relationsResult.status==='fulfilled')relations=relationsResult.value.relations||[];if(leadersResult.status==='fulfilled'&&positionsResult.status==='fulfilled')applyLeaderMetadata(leadersResult.value,positionsResult.value);else console.error('Métadonnées de factions/positions incomplètes',leadersResult,positionsResult);metadataLoading=false;setFooter();render()});