'use client';

import { useMemo, useState } from 'react';
import { dataset } from '../data/prototype';

type Lord = { id: string; name: string; faction: string; race: string; crest: string };
type Modifier = { label: string; value: number };
type Relation = { from: string; to: string; modifiers: Modifier[]; status: 'Favorable' | 'Neutre' | 'Hostile' };

const legacyDataset = {
  gameVersion: 'Immortal Empires · fixture prototype', verification: 'unverified' as const,
  lords: [
    { id: 'imrik', name: 'Imrik', faction: 'Knights of Caledor', race: 'Haut Elfe', crest: '✦' }, { id: 'karl', name: 'Karl Franz', faction: 'Reikland', race: 'Empire', crest: '♜' }, { id: 'malus', name: 'Malus Darkblade', faction: 'Hag Graef', race: 'Elfe Noir', crest: '☾' }, { id: 'kugath', name: "Ku'gath Plaguefather", faction: 'Poxmakers of Nurgle', race: 'Nurgle', crest: '☣' }, { id: 'tyrion', name: 'Tyrion', faction: 'Eataine', race: 'Haut Elfe', crest: '☀' }, { id: 'thorgrim', name: 'Thorgrim Grudgebearer', faction: 'Dwarfs', race: 'Nain', crest: '⛰' },
  ] satisfies Lord[],
  relations: [
    ['imrik','karl','Favorable', [['Affinité des races',20],['Confiance lointaine',5]]], ['karl','imrik','Favorable',[['Affinité des races',20]]], ['imrik','malus','Hostile',[['Aversion elfes noirs',-40],['Rivalité historique',-10]]], ['malus','imrik','Hostile',[['Aversion haut elfes',-45]]], ['imrik','kugath','Hostile',[['Aversion Chaos',-60]]], ['kugath','imrik','Hostile',[['Opposition à l’Ordre',-55]]], ['karl','malus','Hostile',[['Aversion elfes noirs',-30]]], ['malus','karl','Hostile',[['Mépris de l’Empire',-35]]], ['karl','kugath','Hostile',[['Aversion Chaos',-60]]], ['kugath','karl','Hostile',[['Opposition à l’Ordre',-60]]], ['malus','kugath','Neutre',[['Intérêts divergents',-5]]], ['kugath','malus','Neutre',[['Indifférence',0]]],
  ].map(([from,to,status,modifiers]) => ({from: from as string,to: to as string,status: status as Relation['status'],modifiers: (modifiers as [string,number][]).map(([label,value]) => ({label,value}))})) satisfies Relation[],
};
const score = (relation?: Relation) => relation?.modifiers.reduce((sum, item) => sum + item.value, 0) ?? 0;
const tone = (value: number) => value > 0 ? 'positive' : value < 0 ? 'negative' : 'neutral';

export default function Home() {
  const [selectedIds, setSelectedIds] = useState(['imrik', 'karl', 'malus', 'kugath']); const [query, setQuery] = useState(''); const [race, setRace] = useState('Toutes les races'); const [focused, setFocused] = useState<Relation | null>(dataset.relations[0]);
  const selected = dataset.lords.filter((lord) => selectedIds.includes(lord.id)); const races = ['Toutes les races', ...Array.from(new Set(dataset.lords.map((lord) => lord.race)))];
  const choices = useMemo(() => dataset.lords.filter((lord) => lord.name.toLowerCase().includes(query.toLowerCase()) && (race === 'Toutes les races' || lord.race === race)), [query, race]);
  const teamRelations = dataset.relations.filter((relation) => selectedIds.includes(relation.from) && selectedIds.includes(relation.to)); const worst = [...teamRelations].sort((a, b) => score(a) - score(b))[0];
  const leader = selected[0]; const leaderRelations = dataset.relations.filter((relation) => relation.from === leader?.id).sort((a, b) => score(b) - score(a));
  const toggle = (id: string) => setSelectedIds((current) => current.includes(id) ? current.filter((item) => item !== id) : current.length < 4 ? [...current, id] : current);
  return <main><section className="hero"><nav><a className="brand" href="#top"><span>✦</span> WH3 <em>Diplomacy</em></a><div className="nav-note">Immortal Empires <i /> Outil communautaire</div></nav><div className="hero-copy" id="top"><p className="eyebrow">Prépare ta campagne multijoueur</p><h1>Formez une alliance<br/><strong>qui tient la route.</strong></h1><p className="lede">Compare les affinités diplomatiques de départ entre seigneurs légendaires, avant le premier tour.</p><a href="#composer" className="start">Composer une équipe <b>↓</b></a></div><div className="sigil sigil-a">✦</div><div className="sigil sigil-b">☉</div></section>
    <section className="workspace" id="composer"><header className="section-head"><div><p className="eyebrow">01 · Ton équipe</p><h2>Qui part à l’aventure&nbsp;?</h2></div><span className="count">{selected.length} / 4 sélectionnés</span></header><div className="composer-grid"><aside className="picker"><div className="search"><span>⌕</span><input aria-label="Rechercher un seigneur" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Rechercher un seigneur..."/></div><div className="filters">{races.map((item) => <button onClick={() => setRace(item)} className={race === item ? 'active' : ''} key={item}>{item}</button>)}</div><div className="lord-list">{choices.map((lord) => <button onClick={() => toggle(lord.id)} className={`lord ${selectedIds.includes(lord.id) ? 'picked' : ''}`} key={lord.id}><span className="crest">{lord.crest}</span><span><b>{lord.name}</b><small>{lord.faction} · {lord.race}</small></span><i>{selectedIds.includes(lord.id) ? '✓' : '+'}</i></button>)}</div></aside><div className="selection"><p className="selection-label">Équipe sélectionnée</p><div className="team">{selected.map((lord) => <article key={lord.id} className="team-card"><button aria-label={`Retirer ${lord.name}`} onClick={() => toggle(lord.id)}>×</button><span className="crest large">{lord.crest}</span><p>{lord.name}</p><small>{lord.faction}</small></article>)}</div><p className="hint">Sélectionne entre 2 et 4 dirigeants pour analyser leurs relations initiales.</p></div></div></section>
    {selected.length >= 2 && <section className="matrix-section"><header className="section-head"><div><p className="eyebrow">02 · Compatibilité</p><h2>La table des relations</h2></div><p className="matrix-help">Chaque case lit une relation directionnelle <b>A → B</b>.</p></header><div className="matrix-wrap"><table className="matrix"><thead><tr><th>De / Vers</th>{selected.map((lord) => <th key={lord.id}><span className="crest tiny">{lord.crest}</span>{lord.name.split(' ')[0]}</th>)}</tr></thead><tbody>{selected.map((from) => <tr key={from.id}><th><span className="crest tiny">{from.crest}</span>{from.name}</th>{selected.map((to) => { const relation = dataset.relations.find((item) => item.from === from.id && item.to === to.id); const value = score(relation); return <td key={to.id}>{from.id === to.id ? <span className="self">—</span> : <button onClick={() => setFocused(relation ?? null)} className={`relation ${tone(value)}`}><b>{value > 0 ? '+' : ''}{value}</b><small>{relation?.status ?? 'Neutre'}</small></button>}</td>})}</tr>)}</tbody></table></div><div className="legend"><span><i className="dot positive"/> Favorable</span><span><i className="dot neutral"/> Neutre</span><span><i className="dot negative"/> Hostile</span><span>Cliquer une relation pour le détail</span></div></section>}
    <section className="insights"><div className="summary"><p className="eyebrow">03 · Verdict</p><h2>Attention aux tensions</h2><p>Votre équipe comporte des relations difficiles. Elles peuvent rendre les premiers tours diplomatiques plus exigeants.</p>{worst && <div className="warning"><span>⚠</span><div><small>Point de friction principal</small><b>{dataset.lords.find((l) => l.id === worst.from)?.name} → {dataset.lords.find((l) => l.id === worst.to)?.name}</b><em>{score(worst)} · {worst.status}</em></div></div>}</div><aside className="breakdown"><p className="eyebrow">Détail de la relation</p>{focused ? <><h3>{dataset.lords.find((l) => l.id === focused.from)?.name} <span>→</span> {dataset.lords.find((l) => l.id === focused.to)?.name}</h3><div className={`big-score ${tone(score(focused))}`}>{score(focused) > 0 ? '+' : ''}{score(focused)} <small>{focused.status}</small></div><div className="modifiers">{focused.modifiers.map((modifier) => <div key={modifier.label}><span>{modifier.label}<small>Fixture non vérifiée</small></span><b className={tone(modifier.value)}>{modifier.value > 0 ? '+' : ''}{modifier.value}</b></div>)}</div></> : <p className="empty-detail">Sélectionne une relation dans la matrice.</p>}</aside></section>
    {leader && <section className="leader-view"><p className="eyebrow">04 · Vue dirigeant</p><h2>Les relations de {leader.name}</h2><p>Classement des factions connues, du meilleur au pire.</p><div className="leader-results">{leaderRelations.map((relation) => { const target = dataset.lords.find((item) => item.id === relation.to); return <button onClick={() => setFocused(relation)} className={`leader-row ${tone(score(relation))}`} key={relation.to}><span className="crest">{target?.crest}</span><span><b>{target?.name}</b><small>{target?.faction} · {target?.race}</small></span><em>{score(relation) > 0 ? '+' : ''}{score(relation)}</em><i>{relation.status}</i></button>})}</div></section>}<footer><span>WH3 Diplomacy · Données de prototype</span><span className="unverified">● Données non vérifiées — en attente de l’importeur</span></footer></main>;
}
