"use client";
import { useMemo,useState } from "react";
import { dataset, type Relation } from "../data/prototype";
import ImmortalEmpiresMap from "./ImmortalEmpiresMap";
const score=(r?:Relation)=>r?.modifiers.reduce((s,m)=>s+m.value,0)??0;
export default function Home(){
 const [selectedIds,setSelectedIds]=useState(["imrik","karl","malus","kugath"]); const [query,setQuery]=useState(""); const [race,setRace]=useState("Toutes les races");
 const selected=dataset.lords.filter(l=>selectedIds.includes(l.id)); const races=["Toutes les races",...Array.from(new Set(dataset.lords.map(l=>l.race)))];
 const choices=useMemo(()=>dataset.lords.filter(l=>(l.name+" "+l.faction).toLowerCase().includes(query.toLowerCase())&&(race==="Toutes les races"||l.race===race)),[query,race]);
 const toggle=(id:string)=>setSelectedIds(c=>c.includes(id)?c.filter(x=>x!==id):c.length<4?[...c,id]:c);
 return <main><section className="hero"><nav><a className="brand" href="#top"><span>✦</span> WH3 <em>Diplomacy</em></a><div className="nav-note">Immortal Empires <i/> Outil communautaire</div></nav><div className="hero-copy" id="top"><p className="eyebrow">Prépare ta campagne multijoueur</p><h1>Formez une alliance<br/><strong>qui tient la route.</strong></h1><p className="lede">Compare les factions, leurs relations de départ et leur éloignement géographique.</p><a href="#composer" className="start">Composer une équipe <b>↓</b></a></div></section>
 <section className="workspace" id="composer"><header className="section-head"><div><p className="eyebrow">01 · Ton équipe</p><h2>Choisis tes seigneurs</h2></div><span className="count">{selected.length} / 4 sélectionnés</span></header><div className="composer-grid"><aside className="picker"><div className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Seigneur ou faction..."/></div><div className="filters">{races.map(r=><button className={race===r?"active":""} onClick={()=>setRace(r)} key={r}>{r}</button>)}</div><div className="lord-list">{choices.map(l=><button className={`lord ${selectedIds.includes(l.id)?"picked":""}`} onClick={()=>toggle(l.id)} key={l.id}><span className="crest">{l.crest}</span><span><b>{l.name}</b><small>{l.faction} · {l.race}</small></span><i>{selectedIds.includes(l.id)?"✓":"+"}</i></button>)}</div></aside><div className="selection"><p className="selection-label">Équipe sélectionnée</p><div className="team">{selected.map(l=><article className="team-card" key={l.id}><button onClick={()=>toggle(l.id)}>×</button><span className="crest large">{l.crest}</span><p>{l.name}</p><small>{l.faction}</small></article>)}</div></div></div></section>
 {selected.length>=2&&<section className="matrix-section"><header className="section-head"><div><p className="eyebrow">02 · Compatibilité</p><h2>Relations diplomatiques</h2></div></header><div className="matrix-wrap"><table className="matrix"><thead><tr><th>De / Vers</th>{selected.map(l=><th key={l.id}>{l.name}</th>)}</tr></thead><tbody>{selected.map(from=><tr key={from.id}><th>{from.name}</th>{selected.map(to=>{if(from.id===to.id)return <td key={to.id}>—</td>;const r=dataset.relations.find(x=>x.from===from.id&&x.to===to.id);return <td key={to.id}>{r?<b>{score(r)}</b>:<span className="unverified">Non extraite</span>}</td>})}</tr>)}</tbody></table></div><p className="map-source">Les valeurs absentes ne sont pas converties en zéro : #1/#5 doit les reconstruire depuis les données du jeu.</p></section>}
 <ImmortalEmpiresMap lords={selected}/><footer><span>WH3 Diplomacy · Immortal Empires</span><span className="unverified">● Données partielles et traçables</span></footer></main>;
}